### PR TITLE
Whole refactor

### PR DESCRIPTION
**Pull request by Anreol**
Tried to add scepter to my mod, not only it was hard to see how it's done but also hard how you actually get there, just awful all around, to the point where someone had to send me a code snip to copy and paste.
The file organization is awful, there's basically no namespace usage, methods that shouldn't be public are public, and there's absolutely zero documentation comments. Even had some issues when looking at the code through the github repo because everything was everywhere.

The goal is to replace and remove everything that is redundant, simplifying and cleaning code, making the whole project understandable. *Old mods should still be able to access the old legacy method to add skills*
Also adding new features, such as "ReservesASlotNoImplementation" so this mod doesn't do anything, letting the entire implementation be on the other mod's side, but so this mod doesn't delete the scepter item due to it "having no use"

- [x] General Re-structure with new classes and proper namespaces
- [x] Moved code around to their proper places
- [ ] Implement proper language support using the game's language system (Fixing #34)
- [ ] Implement AncientScepterContent and store all relevant data in their proper classes (Skills, Buffs, etc) like how RoR2Content and DLC1Content does
- [ ] Review ReservesASlotNoImplementation (It could be just a flag / boolean field?)
- [ ] Finish rewriting the mod's logic (Originally all in AncientScepterItem)
- [ ] Strip out AncientScepterItem off all logic that isn't required to keep support with old mods (Delete everything but RegisterScepterSkills)
- [ ] Make it compile
- [ ] Make sure things still work
- [ ] ???

This would be a nice time to add support for fixing #30 

Also, while upgraded scepter skills should be their own entity states, instead of hacking the original skill's state with some hooks, as other mods (ie. RiskyMod) might touch on those, so scepter skills should be standalone, that seems like too much work for me right now.
Additionally, moving content such as SkillDefs to the Unity assetbundle so they don't have to be entirely created through code would be nice, but I haven't even opened that yet, and I'm not sure if it works.

Making this draft pull request to gather feedback and so other people might help with this.

### CODE REVIEW

**Comment by yekoc** [comment]
Hook to proper New Skill conversion checklist.(I'll handle em)

- [ ] Acrid
- [ ] Arti
- [ ] Bandit
- [ ] Captain (Consider replacement effect, #30 )
- [ ] Commando
- [ ] Engi
- [ ] Heretic (Consider replacement effect, previous discussions mentioned something with Ruin)
- [ ] Huntress
- [ ] Loader
- [ ] Merc
- [ ] Mul-T
- [ ] Railgunner
- [ ] REX
- [ ] Viend (Consider replacement effect, previous discussions mentioned current is underwhelming)

**Comment by Anreol** [comment]
Oh also, I haven't written anything related to this in the code, but I thought that it would be more proper to have entirely new States (ie. inside EntityStates) for each Scepter skill, inheriting from the State that they are upgrading, so they have the ability to have their own Entity State Configuration file, and maybe to override or append some behavior, too.

**Comment by yekoc** [comment]
That _was_ the intention I was going for when I put up the checklist,indeed. :^)

**Comment by Anreol** [comment]
Been busy with work, might work on it next week since I have some holidays, but at the same time: holidays, so I can't make any promises.

**Comment by DestroyedClone** [comment]
@Anreol Are you still intending on finishing this PR?

**Comment by Anreol** [comment]
My bad, I'm not, so I guess I'll close it. Anybody can feel free to finish it.

**Pull request closed without merging**
